### ISSUE TITLE
useQuery - No overload matches this call. 

### ISSUE THREAD

**Issue by ertolv** [alan2207/bulletproof-react#60] opened 2022-02-14 13:37 UTC
I am getting this error for all instances when `useQuery` is used.
```
TypeScript error in C:/Users/abcdef/vscodeProjects/bulletproof/src/features/comments/api/getComments.ts(22,10):
No overload matches this call.
  Overload 1 of 3, '(options: UseQueryOptions<Comment[], unknown, Comment[], string[]>): UseQueryResult<Comment[], unknown>', gave the following error.
    Argument of type '{ queryKey: string[]; queryFn: () => Promise<Comment[]>; enabled?: boolean | undefined; staleTime?: number | undefined; refetchInterval?: number | false | ((data: Comment[] | undefined, query: Query<...>) => number | false) | undefined; ... 29 more ...; meta?: QueryMeta | undefined; }' is not assignable to parameter of type 'UseQueryOptions<Comment[], unknown, Comment[], string[]>'.
      Types of property 'refetchInterval' are incompatible.
        Type 'number | false | ((data: Comment[] | undefined, query: Query<Comment[], unknown, Comment[], QueryKey>) => number | false) | undefined' is not assignable to type 'number | false | ((data: Comment[] | undefined, query: Query<Comment[], unknown, Comment[], string[]>) => number | false) | undefined'.
          Type '(data: Comment[] | undefined, query: Query<Comment[], unknown, Comment[], QueryKey>) => number | false' is not assignable to type 'number | false | ((data: Comment[] | undefined, query: Query<Comment[], unknown, Comment[], string[]>) => number | false) | undefined'.
            Type '(data: Comment[] | undefined, query: Query<Comment[], unknown, Comment[], QueryKey>) => number | false' is not assignable to type '(data: Comment[] | undefined, query: Query<Comment[], unknown, Comment[], string[]>) => number | false'.
              Types of parameters 'query' and 'query' are incompatible.
                Type 'Query<Comment[], unknown, Comment[], string[]>' is not assignable to type 'Query<Comment[], unknown, Comment[], QueryKey>'.
                  The types of 'options.queryFn' are incompatible between these types.
                    Type 'QueryFunction<Comment[], string[]> | undefined' is not assignable to type 'QueryFunction<Comment[], QueryKey> | undefined'.
                      Type 'QueryFunction<Comment[], string[]>' is not assignable to type 'QueryFunction<Comment[], QueryKey>'.
                        Type 'QueryKey' is not assignable to type 'string[]'.
                          Type 'string' is not assignable to type 'string[]'.
  Overload 2 of 3, '(queryKey: QueryKey, options?: Omit<UseQueryOptions<unknown, unknown, unknown, QueryKey>, "queryKey"> | undefined): UseQueryResult<unknown, unknown>', gave the following error.
    Argument of type '{ queryKey: string[]; queryFn: () => Promise<Comment[]>; enabled?: boolean | undefined; staleTime?: number | undefined; refetchInterval?: number | false | ((data: Comment[] | undefined, query: Query<...>) => number | false) | undefined; ... 29 more ...; meta?: QueryMeta | undefined; }' is not assignable to parameter of type 'QueryKey'.
      Object literal may only specify known properties, and 'queryKey' does not exist in type 'readonly unknown[]'.  TS2769

    20 | 
    21 | export const useComments = ({ discussionId, config }: UseCommentsOptions) => {
  > 22 |   return useQuery({
       |          ^
    23 |     ...config,
    24 |     queryKey: ['comments', discussionId],
    25 |     queryFn: () => getComments({ discussionId }),
```

**Comment by alan2207** [comment] 2022-02-17 00:25
It was caused by a newer `react-query` version: https://github.com/tannerlinsley/react-query/issues/2753
The issue has been resolved with this commit: https://github.com/alan2207/bulletproof-react/commit/32ed545844f93da00f0b9d4fd3154c475d4773df
Thanks for reporting.

**Closed by alan2207** 2022-02-17 00:25 UTC

**Comment by diegods-ferreira** [comment] 2022-11-29 22:18
I'm having a problem that looks like this one, but I'm now using React Query V4...

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ mutationFn: ({ data }: UpdateUserDTO) => Promise<AuthUser>; context?: React.Context<QueryClient | undefined> | undefined; ... 10 more ...; meta?: MutationMeta | undefined; }' is not assignable to parameter of type 'MutationKey'.
      Object literal may only specify known properties, and 'mutationFn' does not exist in type 'readonly unknown[]'.ts(2769)
useMutation.d.ts(6, 25): The last overload is declared here.
```

I wasn't able to fix it yet =/

**Comment by geoff-harper** [comment] 2023-02-09 21:30
`PromiseValue` was removed in `type-fest` v3 

https://github.com/sindresorhus/type-fest/commit/28f3e481eb6c5d7fba465fa9fed23889c9a6685b

You can now use the built in `Awaited` type in the `react-query ` lib file
